### PR TITLE
Shutdown north when SIGINT or SIGTERM is received

### LINKED ISSUE #103: Make sure all resources are cleaned up when the north runtime exits
Exit scenarios:
- graceful shutdown
- killed by SIGINT
- crash because of panic (panic handler needed)

### PR DESCRIPTION
**Pull request by alfonsoros88**
fixes #103

### CODE REVIEW

File: north/src/runtime/mod.rs [hunk 1]
```diff
@@ -113,6 +113,22 @@ pub async fn run(config: &Config) -> Result<()> {
         state.applications.len()
     );
 
+    // handle SIGINT and SIGTERM
+    let tx_interrupt = tx.clone();
+    ctrlc::set_handler(move || {
```
Comment (flxo) [inline north/src/runtime/mod.rs:118]: Why not moving a copy of the tx handle of the main event loop to the handler? This would be way simpler.

Comment (flxo) [inline north/src/runtime/mod.rs:118]: Installing a signal handler catches a signal. Think this means that the signal is not sent to childs? This is something we would need.

File: north/src/runtime/mod.rs [hunk 2]
```diff
@@ -113,6 +113,22 @@ pub async fn run(config: &Config) -> Result<()> {
...
+            payload: api::Payload::Request(api::Request::Shutdown),
+        };
+        let (tx, rx) = sync::channel::<api::Message>(1);
+        async_std::task::block_on(tx_interrupt.send(Event::Console(request, tx)));
+
+        if async_std::task::block_on(rx.recv()).is_err() {
+            panic!("Failed to shutdown north");
+        }
+    })
+    .expect("Failed to set signal handler");
```
Comment (flxo) [inline north/src/runtime/mod.rs:130]: No need to expect something in a fn that return `Result`.

File: north/src/runtime/mod.rs (hunk 1 above)
Comment (alfonsoros88) [reply north/src/runtime/mod.rs:120]: this is exactly what this is doing, isn't it?

File: north/Cargo.toml [hunk 3]
```diff
@@ -45,6 +45,7 @@ toml = { version = "0.5.6", optional = true }
 url = { version = "2.1.1", optional = true }
 uuid = { version = "0.8.1", features = [ "v4"], optional = true }
 zip = { version = "0.5.6", optional = true }
+ctrlc = { version = "3.1.6", features = ["termination"] }
```
Comment (flxo) [inline north/Cargo.toml:48]: nit: sort dependencies alphanumerically

Why is this a feature? Think we can have this all the time.

File: north/src/runtime/mod.rs [hunk 4]
```diff
@@ -113,6 +113,13 @@ pub async fn run(config: &Config) -> Result<()> {
         state.applications.len()
     );
 
+    // Handle SIGINT and SIGTERM
+    let tx_interrupt = tx.clone();
+    ctrlc::set_handler(move || {
```
Comment (flxo) [inline north/src/runtime/mod.rs:118]: This won't compile if feature `termination` is not enabled and it's not enabled by default.

File: north/src/runtime/state.rs [hunk 5]
```diff
@@ -319,6 +311,20 @@ impl State {
         }
     }
 
+    /// Stop and uninstall all the applications
+    pub async fn stop_and_uninstall_all(&mut self) -> result::Result<(), Error> {
```
Comment (flxo) [inline north/src/runtime/state.rs:315]: I'd rename this to `shutdown`

**Review by flxo — CHANGES_REQUESTED** [review]

File: north/src/runtime/state.rs (hunk 5 above)
Comment (alfonsoros88) [reply north/src/runtime/state.rs:315]: That would conflict with the console shutdown function. The difference is that shutdown won't do anything if any container is running. Maybe "cleanup" or "tear_down" is a better name for this function?

File: north/src/runtime/mod.rs (hunk 4 above)
Comment (alfonsoros88) [reply north/src/runtime/mod.rs:118]: It does compile without the `termination` feature. It will just not handle `SIGTERM` as well.

File: north/Cargo.toml (hunk 3 above)
Comment (alfonsoros88) [reply north/Cargo.toml:48]: This  feature makes the handle catch `SIGTERM` in addition to `SIGINT`.
